set_property SRC_FILE_INFO {cfile:/home/parallels/Desktop/ProjetosVivado/PCR_P1/Neoronio_2.srcs/constrs_1/new/timing_analysis.xdc rfile:../../../Neoronio_2.srcs/constrs_1/new/timing_analysis.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clkin -max 0.750 [get_ports en]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_input_delay -clock clkin -min 0.500 [get_ports en]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clkin -max 2 [get_ports led]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_output_delay -clock clkin -min 1 [get_ports led]
