# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/parallels/Desktop/ProjetosVivado/Basys3_Master.xdc

# XDC: new/timing_analysis.xdc

# IP: ip/ROMmenXir/ROMmenXir.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROMmenXir || ORIG_REF_NAME==ROMmenXir} -quiet] -quiet
