# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/filipesfreitas/Documentos/calculo_desvio/calculo_desvio.cache/wt [current_project]
set_property parent.project_path /home/filipesfreitas/Documentos/calculo_desvio/calculo_desvio.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo /home/filipesfreitas/Documentos/calculo_desvio/calculo_desvio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet /home/filipesfreitas/Circuitos_Reconfiguraveis/operadorFloatingPoint/multiplierfsm_v2.dcp
set_property used_in_implementation false [get_files /home/filipesfreitas/Circuitos_Reconfiguraveis/operadorFloatingPoint/multiplierfsm_v2.dcp]
read_vhdl -library xil_defaultlib {
  /home/filipesfreitas/Circuitos_Reconfiguraveis/operadorFloatingPoint/fpupack.vhd
  /home/filipesfreitas/Circuitos_Reconfiguraveis/operadorFloatingPoint/entities.vhd
  /home/filipesfreitas/Circuitos_Reconfiguraveis/operadorFloatingPoint/multiplierfsm_v2.vhd
  /home/filipesfreitas/Documentos/calculo_desvio/calculo_desvio.srcs/sources_1/new/desvio_velocidade.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top desvio_velocidade -part xc7a35tcpg236-1 -fanout_limit 400 -fsm_extraction one_hot -keep_equivalent_registers -resource_sharing off -no_lc -shreg_min_size 5


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef desvio_velocidade.dcp
create_report "synth_2_synth_report_utilization_0" "report_utilization -file desvio_velocidade_utilization_synth.rpt -pb desvio_velocidade_utilization_synth.pb"
