# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/parallels/Desktop/ProjetosVivado/PCR_P1/Neoronio_2.srcs/sources_1/ip/ROMmenXul/ROMmenXul.xci
# IP: The module: 'ROMmenXul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/Desktop/ProjetosVivado/PCR_P1/Neoronio_2.srcs/sources_1/ip/ROMmenXul/ROMmenXul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROMmenXul'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/parallels/Desktop/ProjetosVivado/PCR_P1/Neoronio_2.srcs/sources_1/ip/ROMmenXul/ROMmenXul.xci
# IP: The module: 'ROMmenXul' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/parallels/Desktop/ProjetosVivado/PCR_P1/Neoronio_2.srcs/sources_1/ip/ROMmenXul/ROMmenXul_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROMmenXul'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
